name: Build Docker Image and Push

on:
    push:
        branches:
            - "master"

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2.3.0
              with:
                  push: true
                  tags: ericmathison/nginx-nocache:latest, ericmathison/nginx-nocache:1, ericmathison/nginx-nocache:1.19, ericmathison/nginx-nocache:1.19-fastcgi
            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
